// Module loader for pages
const {
  agenda,
  agendaEvent,
  agendaMeetingEvent,
  people,
} = require('./agenda');
const {
  VideoProjectsBar,
  ExperiencesSettingsBar,
  SettingsSubNav,
  CatalogueHome,
  ImmersionHome,
  LiveEventHome,
} = require('./experiences_page');
const {
  ChooseTemplateHeader,
  TemplateFilterBar,
  Templates,
  ExperienceOverview
} = require('./create_experience_page');
const {
  Subnav,
  Components,
  Interactivity,
  ManageCollection,
  EditCollection,
  PublishingHeader,
  PublishSiteModal,
  SidebarStyle,
  VideoSetting,
  SharingOptions,
  Tracking,
  TemplateSettings,
  HeaderAndFooter,
  AddAgenda,
  Agenda,
  Auth0,
  Toaster,
  SEO
} = require('./edit_experience_page');
const { Publishedapp2, Publishedapp1 } = require('./published_experience_page');
const { Player } = require('./player');
const {
  CustomPage,
  CustomPageErrorMsg,
  isErrorCodeMatching,
  PageLink,
  SectionType,
  HeadlineType,
  GetSection,
  CustomPageUpdatedText,
  TextFontSize,
  TextLineHt,
  moveOptions,
  customSelectAgenda,
  customAgendaWidget,
} = require('./custom_page');
const {
  vcHelp,
  community,
  gainSightRequestLogger,
  gainSightRequestMock,
} = require('./community_page');

module.exports = {
  agenda,
  agendaEvent,
  agendaMeetingEvent,
  people,
  VideoProjectsBar,
  ExperiencesSettingsBar,
  SettingsSubNav,
  ChooseTemplateHeader,
  TemplateFilterBar,
  Templates,
  ExperienceOverview,
  Subnav,
  Components,
  Interactivity,
  ManageCollection,
  EditCollection,
  PublishingHeader,
  PublishSiteModal,
  SidebarStyle,
  VideoSetting,
  SharingOptions,
  Tracking,
  TemplateSettings,
  HeaderAndFooter,
  AddAgenda,
  Agenda,
  Auth0,
  Toaster,
  SEO,
  Publishedapp2,
  Publishedapp1,
  Player,
  CatalogueHome,
  ImmersionHome,
  LiveEventHome,
  CustomPage,
  CustomPageErrorMsg,
  isErrorCodeMatching,
  PageLink,
  SectionType,
  HeadlineType,
  GetSection,
  CustomPageUpdatedText,
  TextFontSize,
  TextLineHt,
  moveOptions,
  customSelectAgenda,
  customAgendaWidget,
  vcHelp,
  community,
  gainSightRequestLogger,
  gainSightRequestMock,
};